version: "3"

services:
  nginx:
    build:
      context: ./nginx

    container_name: nginx

    tty: true

    ports:
      - "8080:80"

    depends_on:
      - app

    networks:
      - desafio-networks

  app:
    build:
      context: ./node

    container_name: app

    entrypoint: dockerize -wait tcp://bd:3306 -timeout 20s

    tty: true

    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules

    command: ["node", "index.js"]

    depends_on:
      - bd

    networks:
      - desafio-networks

  bd:
    container_name: bd

    image: mysql:5.7

    command: --innodb-use-native-aio=0

    restart: always

    tty: true

    volumes:
      - ./mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

    networks:
      - desafio-networks

networks:
  desafio-networks:
    driver: bridge
