version: '3'

services:

  nginx:
    container_name: nginx
    tty: true
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - desafio-fullcycle
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./node:/usr/src/app
      - ./usr/src/app/node_modules
    entrypoint: dockerize -wait tcp://mybd:3306 -timeout 60s  docker-entrypoint.sh node index.js
    networks:
      - desafio-fullcycle
    depends_on:
      - mybd

  mybd:
    container_name: mybd
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-fullcycle

networks:
  desafio-fullcycle:
    driver: bridge